### ISSUE TITLE
Can't send files using android 10 device 

### ISSUE THREAD

**Issue by kishansinghpanwar** [trebleshot/android#141] opened 2020-07-31 06:12 UTC
The bug appears when i'm trying to send the file android-10 to android 9, 
I've started the Hotspot in 1 device of  android-9 and trying to send file using android-10 device, while scanning the QR code it's trying to connect with the other phone till 1-2 minutes and after 5-7 tries getting popup message, unable to connect
I'm getting this message in Logcat : 

> establishHotspotConnection(): Connection check ping failed

but same if i start the hotspot in android 10 and send the file from android-9 to android-10 it's working fine.

**Comment by njamal816** [comment] 2020-07-31 18:13
Try disabling mobile data in the android 10 (scanning device) and try again. Mostly that will fix. Issue with latest android is that if there is data enabled and the wifi trying to connect don't have data, it will not connect properly to that wifi. Fixed the issue in my modified version doing that.

**Comment by kishansinghpanwar** [comment] 2020-08-01 05:42
@njamal816 I've checked this but still not working, when i'm trying to scan using android 10 device, as you mentioned can you please give me a link of commit or source to know where is your updated version, so i can check once in my android 10 devices.

**Comment by ahmadarslan13** [comment] 2020-08-02 21:39
Yes there is an issue on android 10 
Targetsdk 29 is not working on android 10 but on lower version it works

**Comment by velitasali** [comment] 2020-09-01 19:48
Duplicate of #139

**Closed by velitasali** 2020-09-01 19:48 UTC
