### ISSUE TITLE
I need to implement hotspot fragment from contantsharing activity to derect hotspot fragment without any crash 

### ISSUE THREAD

**Issue by safeeraliPS** [trebleshot/android#153] opened 2020-11-30 16:13 UTC
Hi ,
I need to implement derect contantsharingactivity to hotsportmanagerfragment without crash I have implimented that but after show qrcode when I click back button it getting crash and I need to avoid adddevice activity and connectionmanageractivity 
And when receive it need to show qrcode scanner activity without any crash
And application fragments need to in gridview if possible 
Please help
Thanks

**Comment by velitasali** [comment] 2020-11-30 19:41
Duplicate of #150

**Closed by velitasali** 2020-11-30 19:41 UTC
