### ISSUE TITLE
When scanning QRCode it shows me Connection Failed

### ISSUE THREAD

**Issue by lokeshdesai403** [trebleshot/android#130] opened 2020-07-06 15:58 UTC
When scanning QRCode it shows me Connection Failed

1. Go to QRCode Scanner screen.
2. Scan QRCode from other devices
3. It will show you "Connection Failed" some times.

**Expected behavior**
It should scan QRCode and Just get connected with other device

 java.net.ConnectException: failed to connect to /192.168.0.1 (port 1128) from /:: (port 41591): connect failed: ECONNREFUSED (Connection refused)
2020-07-06 21:23:17.379 21327-22001/? W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:143)
2020-07-06 21:23:17.379 21327-22001/? W/System.err:     at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
2020-07-06 21:23:17.380 21327-22001/? W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
2020-07-06 21:23:17.381 21327-22001/? W/System.err:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
2020-07-06 21:23:17.381 21327-22001/? W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
2020-07-06 21:23:17.382 21327-22001/? W/System.err:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
2020-07-06 21:23:17.382 21327-22001/? W/System.err:     at java.net.Socket.connect(Socket.java:621)
2020-07-06 21:23:17.383 21327-22001/? W/System.err:     at java.net.Socket.connect(Socket.java:570)
2020-07-06 21:23:17.383 21327-22001/? W/System.err:     at com.genonbeta.CoolSocket.CoolSocket$ActiveConnection.connect(CoolSocket.java:516)
2020-07-06 21:23:17.384 21327-22001/? W/System.err:     at com.genonbeta.CoolSocket.CoolSocket$Client.connect(CoolSocket.java:804)
2020-07-06 21:23:17.385 21327-22001/? W/System.err:     at com.hapshare.util.CommunicationBridge$Client.connect(CommunicationBridge.java:95)
2020-07-06 21:23:17.386 21327-22001/? W/System.err:     at com.hapshare.util.CommunicationBridge$Client.connectWithHandshake(CommunicationBridge.java:105)
2020-07-06 21:23:17.386 21327-22001/? W/System.err:     at com.hapshare.ui.UIConnectionUtils$4.onConnect(UIConnectionUtils.java:233)
2020-07-06 21:23:17.387 21327-22001/? W/System.err:     at com.hapshare.util.CommunicationBridge.connect(CommunicationBridge.java:47)
2020-07-06 21:23:17.387 21327-22001/? W/System.err:     at com.hapshare.util.CommunicationBridge.connect(CommunicationBridge.java:35)
2020-07-06 21:23:17.388 21327-22001/? W/System.err:     at com.hapshare.ui.UIConnectionUtils.setupConnection(UIConnectionUtils.java:225)
2020-07-06 21:23:17.389 21327-22001/? W/System.err:     at com.hapshare.ui.UIConnectionUtils$3.onRun(UIConnectionUtils.java:147)
2020-07-06 21:23:17.389 21327-22001/? W/System.err:     at com.hapshare.util.InterruptAwareJob.run(InterruptAwareJob.java:16)
2020-07-06 21:23:17.390 21327-22001/? W/System.err:     at com.hapshare.service.WorkerService$RunningTask.run(WorkerService.java:369)
2020-07-06 21:23:17.391 21327-22001/? W/System.err:     at com.hapshare.service.WorkerService$1.run(WorkerService.java:195)
2020-07-06 21:23:17.391 21327-22001/? W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
2020-07-06 21:23:17.392 21327-22001/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-07-06 21:23:17.393 21327-22001/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-07-06 21:23:17.393 21327-22001/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-07-06 21:23:17.394 21327-22001/? W/System.err:     at java.lang.Thread.run(Thread.java:919)
2020-07-06 21:23:17.396 21327-22001/? W/System.err: Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
2020-07-06 21:23:17.396 21327-22001/? W/System.err:     at libcore.io.Linux.connect(Native Method)
2020-07-06 21:23:17.397 21327-22001/? W/System.err:     at libcore.io.ForwardingOs.connect(ForwardingOs.java:95)
2020-07-06 21:23:17.397 21327-22001/? W/System.err:     at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:136)
2020-07-06 21:23:17.398 21327-22001/? W/System.err:     at libcore.io.ForwardingOs.connect(ForwardingOs.java:95)
2020-07-06 21:23:17.398 21327-22001/? W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:157)
2020-07-06 21:23:17.399 21327-22001/? W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:135)
2020-07-06 21:23:17.399 21327-22001/? W/System.err: 	... 24 more

 - Android version: [Android 10]
 - Language: [English]
 - Device Model and Brand [OnePlus6T]

**Comment by beNitinhere** [comment] 2020-07-29 04:29
@lokeshdesai403  Any update?

**Comment by lokeshdesai403** [comment] 2020-07-29 08:27
@beNitinhere Nope still same issue

**Comment by solankiranvir** [comment] 2020-08-14 06:52
Any Update in this issue? Because i have same issue.

**Comment by mjbdl** [comment] 2021-02-19 13:04
> When scanning QRCode it shows me Connection Failed
> 
> Steps to reproduce the behavior:
> 
> 1. Go to QRCode Scanner screen.
> 2. Scan QRCode from other devices
> 3. It will show you "Connection Failed" some times.
> 
> **Expected behavior**
> It should scan QRCode and Just get connected with other device
> 
> java.net.ConnectException: failed to connect to /192.168.0.1 (port 1128) from /:: (port 41591): connect failed: ECONNREFUSED (Connection refused)
> 2020-07-06 21:23:17.379 21327-22001/? W/System.err: at libcore.io.IoBridge.connect(IoBridge.java:143)
> 2020-07-06 21:23:17.379 21327-22001/? W/System.err: at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
> 2020-07-06 21:23:17.380 21327-22001/? W/System.err: at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
> 2020-07-06 21:23:17.381 21327-22001/? W/System.err: at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
> 2020-07-06 21:23:17.381 21327-22001/? W/System.err: at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
> 2020-07-06 21:23:17.382 21327-22001/? W/System.err: at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
> 2020-07-06 21:23:17.382 21327-22001/? W/System.err: at java.net.Socket.connect(Socket.java:621)
> 2020-07-06 21:23:17.383 21327-22001/? W/System.err: at java.net.Socket.connect(Socket.java:570)
> 2020-07-06 21:23:17.383 21327-22001/? W/System.err: at com.genonbeta.CoolSocket.CoolSocket$ActiveConnection.connect(CoolSocket.java:516)
> 2020-07-06 21:23:17.384 21327-22001/? W/System.err: at com.genonbeta.CoolSocket.CoolSocket$Client.connect(CoolSocket.java:804)
> 2020-07-06 21:23:17.385 21327-22001/? W/System.err: at com.hapshare.util.CommunicationBridge$Client.connect(CommunicationBridge.java:95)
> 2020-07-06 21:23:17.386 21327-22001/? W/System.err: at com.hapshare.util.CommunicationBridge$Client.connectWithHandshake(CommunicationBridge.java:105)
> 2020-07-06 21:23:17.386 21327-22001/? W/System.err: at com.hapshare.ui.UIConnectionUtils$4.onConnect(UIConnectionUtils.java:233)
> 2020-07-06 21:23:17.387 21327-22001/? W/System.err: at com.hapshare.util.CommunicationBridge.connect(CommunicationBridge.java:47)
> 2020-07-06 21:23:17.387 21327-22001/? W/System.err: at com.hapshare.util.CommunicationBridge.connect(CommunicationBridge.java:35)
> 2020-07-06 21:23:17.388 21327-22001/? W/System.err: at com.hapshare.ui.UIConnectionUtils.setupConnection(UIConnectionUtils.java:225)
> 2020-07-06 21:23:17.389 21327-22001/? W/System.err: at com.hapshare.ui.UIConnectionUtils$3.onRun(UIConnectionUtils.java:147)
> 2020-07-06 21:23:17.389 21327-22001/? W/System.err: at com.hapshare.util.InterruptAwareJob.run(InterruptAwareJob.java:16)
> 2020-07-06 21:23:17.390 21327-22001/? W/System.err: at com.hapshare.service.WorkerService$RunningTask.run(WorkerService.java:369)
> 2020-07-06 21:23:17.391 21327-22001/? W/System.err: at com.hapshare.service.WorkerService$1.run(WorkerService.java:195)
> 2020-07-06 21:23:17.391 21327-22001/? W/System.err: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
> 2020-07-06 21:23:17.392 21327-22001/? W/System.err: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 2020-07-06 21:23:17.393 21327-22001/? W/System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 2020-07-06 21:23:17.393 21327-22001/? W/System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 2020-07-06 21:23:17.394 21327-22001/? W/System.err: at java.lang.Thread.run(Thread.java:919)
> 2020-07-06 21:23:17.396 21327-22001/? W/System.err: Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
> 2020-07-06 21:23:17.396 21327-22001/? W/System.err: at libcore.io.Linux.connect(Native Method)
> 2020-07-06 21:23:17.397 21327-22001/? W/System.err: at libcore.io.ForwardingOs.connect(ForwardingOs.java:95)
> 2020-07-06 21:23:17.397 21327-22001/? W/System.err: at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:136)
> 2020-07-06 21:23:17.398 21327-22001/? W/System.err: at libcore.io.ForwardingOs.connect(ForwardingOs.java:95)
> 2020-07-06 21:23:17.398 21327-22001/? W/System.err: at libcore.io.IoBridge.connectErrno(IoBridge.java:157)
> 2020-07-06 21:23:17.399 21327-22001/? W/System.err: at libcore.io.IoBridge.connect(IoBridge.java:135)
> 2020-07-06 21:23:17.399 21327-22001/? W/System.err: ... 24 more
> 
> * Android version: [Android 10]
> * Language: [English]
> * Device Model and Brand [OnePlus6T]

Use pro version of Trebleshot
With many features.

https://github.com/Shiv-Shambhu/Leaf-Explorer

**Comment by velitasali** [comment] 2021-08-06 05:28
Duplicate of #161 (closing this one because the logs provided on the other one is on point)

**Closed by velitasali** 2021-08-06 05:28 UTC
Labels: duplicate
