### ISSUE TITLE
SD card recieval support

### ISSUE THREAD

**Issue by Thewisem** [trebleshot/android#165] opened 2021-06-10 06:27 UTC
**Is your feature request related to a problem? Please describe.**
I wanted to have a large file be available to me in SD card as that file is too large for my internal storage. I tried to change the location to somewhere in sd card. But it says it isn't supported.

**Describe the solution you'd like**
To be able to have support for sd card recieval support

**Describe alternatives you've considered**

**Additional context**

**Comment by velitasali** [comment] 2021-07-25 15:59
May be a duplicate of #62.

**Closed by velitasali** 2021-07-25 15:59 UTC
Labels: invalid
