### ISSUE TITLE
Chinese filename went wrong when sending file via browser

### ISSUE THREAD

**Issue by samko5sam** [trebleshot/android#163] opened 2021-05-11 14:28 UTC
### **Describe**
I use browser share mode to send file from desktop to phone.
I go to side bar and click on button "share via browser"

But Chinese filename went wrong when sending file via browser.

**For example:**
The filename to send is **"測試檔案名稱.pdf"**
But sent to phone then the filename become this
![Screenshot_Chinese filename went wrong when sending file via browser](https://user-images.githubusercontent.com/75727536/117831470-2da4f500-b2a7-11eb-981b-fe7d77a24bde.png)

I guess this is an encoding problem(我猜是因為文字編碼的關係而導致的)

**Comment by velitasali** [comment] 2021-05-12 09:31
Duplicate of #149

**Closed** 2021-05-12 09:32 UTC
