### ISSUE TITLE
Crashing App

### ISSUE THREAD

**Issue by sumit7116** [trebleshot/android#148] opened 2020-10-18 13:04 UTC
Its not working on android 10...
**when i change the buildversion and targetsdkversion to 29 or 30 it crashes on android 10.............**
please help me....
Thank you  very much......

**Comment by velitasali** [comment] 2020-10-18 14:24
Duplicate of #146

**Closed by velitasali** 2020-10-18 14:24 UTC

**Comment by sumit7116** [comment] 2020-10-18 14:35
How i can handle that bug please help me
