### ISSUE TITLE
Can't resolve: Unresolved reference: GlideApp

### ISSUE THREAD

**Issue by UltraBurstXD** [trebleshot/android#187] opened 2021-08-31 12:11 UTC
Hi,

I can't figure out `org.monora.uprotocol.client.android.GlideApp`. Is the method missing here or something? I'm receiving many errors because of it. Where does it comes from?

**Comment by velitasali** [comment] 2021-08-31 12:40
It is created by the annotation processor. The fact that you are getting this error doesn't mean that it is the cause. It is highly likely that you have a misconfigured build setup. The app should just build since the CI builds are passing. Restarting the IDE might help if it is behaving weirdly.

**Comment by UltraBurstXD** [comment] 2021-08-31 13:54
Compiler says **Class** "`ApplicationGlideModule`" is never used. May that also contribute too?

**Comment by velitasali** [comment] 2021-08-31 13:58
It means the source files that are going to use that source file are yet to be generated.

**Comment by UltraBurstXD** [comment] 2021-08-31 18:23
What happened to `FilePickerActivity`, `FileExplorerFragment `and `DonationActivity` referenced in layout files `FilePickerActivity`, `activity_file_explorer`,` activity_donation` (Maybe there are more...)? I'm trying to get rid of some errors before rebuild the project once more.

**Comment by velitasali** [comment] 2021-09-01 07:16
All of those those files were removed. I am not sure why you are seeing them. I suggest you check your source tree. You might have made mistake while merging the upstream. 

I am closing this issue now. I hope this resolves your problem!

**Closed by velitasali** 2021-09-01 07:16 UTC
Labels: help wanted
