### ISSUE TITLE
After changing targetSdk 29 app crashes in android 10.

### ISSUE THREAD

**Issue by uttamsharma** [trebleshot/android#146] opened 2020-09-20 02:16 UTC
First of all it's a great application. Thanks for your efforts. 

I Changed targetsdk to 29. 
After installing on device first time open will work finely. 

Next after first app open. Every time app crashes before opening.

**Comment by velitasali** [comment] 2020-09-20 07:14
Obviously, without migrating the code, changing the target SDK will only cause more problems. 

After increasing the target SDK version, you should get rid of the deprecated code and make appropriate changes. 

This issue is not valid at its current form, so I am closing it.

**Closed by velitasali** 2020-09-20 07:14 UTC

**Comment by velitasali** [comment] 2020-09-20 07:15
Duplicate of #139
